### ISSUE TITLE
eww bar setup (newbie)

### ISSUE THREAD

**Issue by wirydotrocks** [hayyaoe/zenities#5] opened 2024-10-03 00:36 UTC
Hello! I was browsing YouTube two weeks ago and decided to install Arch (and Linux in general) for the first time because of your rice!

I wanted to install the `eww` bar onto my desktop and tweak around with it but I have no idea where to start. 
I installed `eww`, and imported your dotfiles for `eww` into my `.config` but all it looks like is this white bar with the widgets not fully loading in properly. I'd like to assume it is white because of `pywal` and my wallpaper, but I'm not so sure.

![1727915373_grim](https://github.com/user-attachments/assets/02acee8b-c4ac-4639-b078-75e761cfd366)

I've tried to run the install script but it messed with some stuff such as my Internet (which I assume because I am on Ethernet) and kitty which I've since uninstalled.

Thank you for being my gateway into Linux! (Also excuse my poor formatting for git, this is also a first for me as well)

**Comment by hayyaoe** [comment] 2024-10-03 01:35
welcome to the linux club, that color problem is caused by pywal, you have to install pywall and load wallpapers with it so pywal generates the color palette in the cache directory. im not really sure about the internet yet but ill try to debug it this week, and do you use the install script or do you just copy the config file, because the bar has some dependencies for it to work properly, also are you using hyprland?

**Comment by wirydotrocks** [comment] 2024-10-03 03:17
Ive installed pywal and generated it for a bunch of stuff actually, do I need to make a pywal config specifically for `eww`?

I should have clarified, I ran `UNINSTALL.SH`, and got rid of the stuff the install script added, and I still use kitty.

At the current moment, I just copied the files to my `.config` and thats all I did so far

I am also on hyprland!

**Comment by hayyaoe** [comment] 2024-10-03 04:29
may i know before you install this configuration for the first time, have you change any of your .config or not?

is it a freshly installed arch hyprland or not?

I just tried to use the unistall script then install it again and had some issues with the stow, but now it works fine by using the install script again.

**Comment by wirydotrocks** [comment] 2024-10-03 04:35
I wouldn't consider this freshly installed as I've been personalizing it little by little starting from two weeks ago.

**Comment by hayyaoe** [comment] 2024-10-03 04:43
I see, the thing with the install script is, i have not test it with a not freshly installed arch hyprland system, its probably because i did not create a backup for some of the configuration on install so the stow errors. 

your problem is probably caused by some missing dependencies.

here is the dependency for the eww if you only want to install the eww bar only by copying the config.
- pamixer
- brightnessctl
- networkmanager
- jq
- gvfs
- socat
- ttf-mononoki
- otf-hermit-nerd
- rofi

also if it still does not work, can you send the `eww logs` and see what is the problem?

**Comment by wirydotrocks** [comment] 2024-10-03 04:44
Sure! 

I should mention i did try to look into the eww logs and see whats going on but i literally had no idea what i was looking at, so thats when I decided to make a git account

Ill let you know what happens!

**Comment by hayyaoe** [comment] 2024-10-03 04:46
you're welcome, I'll be waiting for the logs :)

**Comment by wirydotrocks** [comment] 2024-10-03 06:04
Hello! im back, i got something regarding battery & music in my logs, I am also on a desktop so thats probably part of the problem here

I should also mention that the battery issue repeats itself multiple times in the log, whereas the music issue does not.

```
   │
93 │                   :reveal music-control
   │                           ───────────── `true.false{` is not of type `bool`
   │
   → provided string was not `true` or `false`


/bin/sh: line 2: font-size:: command not found
/bin/sh: -c: line 3: syntax error near unexpected token `}'
/bin/sh: -c: line 3: `}'
warning: The script for the `current-battery`-variable exited unsuccessfully
   ┌─ bar/eww.yuck:42:29
   │
42 │                             "~/.config/eww/bar/scripts/get-battery.sh")
   │                             ────────────────────────────────────────── Defined here
   │
   → Failed with output:
     cat: /sys/class/power_supply//capacity: No such file or directory
```
   
   
   
also eww looks like this now, and right under is your waybar config:
![1291279000815140864remix-1727935330312](https://github.com/user-attachments/assets/4c0f782b-a4e0-4125-886e-da2c40155d33)
(Crossed out my home network just in case)

I had some issue installing ttf-mononoki through the aur (target not found) but I have installed it manually by placing it in `/usr/local/share/fonts`

**Comment by hayyaoe** [comment] 2024-10-03 07:11
do you use pc or laptop?

if you use laptop the battery should be fine but if you use pc the error will be there but it shouldn't affect the bar, 

for the error with the music control i just fixed it and merged it on main branch, you can check it out. 

for the mononoki font you can use the script `yay -S ttf-mononoki"

also can you give the path of the pywal generated colors?
mine is at `~/.cache/wal/colors.scss`

note:
after you use the `wal -i "path"` the pywal generates the color in the directory mine at .cache/wal you have to reopen your eww bar by killing it first, using `killall eww` then `eww open bar`.

**Comment by wirydotrocks** [comment] 2024-10-03 16:49
I am on a pc, and i installed ttf-mononoki successfully, and I've also updated my `eww.yuck`

After taking a look around pywal, I don not have a file at `~/.cache/wal/colors.scss`, and I also dont have a template for `colors.scss` inside of `~/.config/wal/templates`

Is there a template I am missing from pywal or should i write one? (i would have tried writing one out but I do not want to mess anything up)

**Comment by hayyaoe** [comment] 2024-10-04 03:42
you dont have to write the colors.scss, it will be created automatically when pywal is ran by using `wal -i "path to you image"`

sorry, I forgot to mention that you should install the python pywal verison from aur, you can install the python pywal by using the script `yay -S python-pywal`.

or if you write one, here is what the colors.css looks like
```
// SCSS Variables
// Generated by 'wal'
$wallpaper: "/home/abuku/wallpapers/kogecha9revised.jpeg";

// Special
$background: #081928;
$foreground: #c1c5c9;
$cursor: #c1c5c9;

// Colors
$color0: #081928;
$color1: #A4584E;
$color2: #AB8C79;
$color3: #557A85;
$color4: #3BA995;
$color5: #4FAE9B;
$color6: #B29885;
$color7: #c1c5c9;
$color8: #5e6872;
$color9: #A4584E;
$color10: #AB8C79;
$color11: #557A85;
$color12: #3BA995;
$color13: #4FAE9B;
$color14: #B29885;
$color15: #c1c5c9;
```

**Comment by wirydotrocks** [comment] 2024-10-05 05:19
I do have a `colors.css`, and a `colors.scss` file, and I have pywal working on a bunch of my applications now, but eww still stays the same.

I've just tried to reinstall and update the dependencies for the bar but to no avail nothing new has changed

Logs don't show anything else besides battery either.

Is there something that I could possible change in the eww configs that could help it connect to my pywal directories (If that is the only thing that is affecting the look of the bar)?

An idea i had was: Do I have to import the variables from my `colors.scss` into `eww.scss`?

**Comment by hayyaoe** [comment] 2024-10-05 11:24
yes you have import the color.scss from the wal, you can use this as a reference

this is from my eww.scss in my eww directory *not the eww/bar*
```
@import "../../../.cache/wal/colors.scss";

*{
  all: unset;
  font-family: "Mononoki";
  font-weight: bold;
}

@import "bar/eww.scss";
```
you can adjust the `. ./` for the colors.scss

**Comment by wirydotrocks** [comment] 2024-10-07 18:13
Sweet! Sorry I didn't get back to you in time, I was caught up in other work.

Directly pointing that line to my .scss file made this work completely well! This looks great, thank you once again!

I'd like to ask, is it spotify that you use for your music? Would the player on top work with youtube music instead?

**Comment by hayyaoe** [comment] 2024-10-07 18:33
yes, it is spotify clinet called ncspot, and yes you could make the audio controller work for youtube music. ill add that in the next update, so stay tuned 🙌🙌

**Closed** 2024-10-07 18:34 UTC
